
package introsde.APP4.orchestrator.wsdl.app2shed;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShedWebService", targetNamespace = "http://soap.sheds.APP2.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShedWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.APP4.orchestrator.wsdl.app2shed.Shed
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addShed", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.AddShed")
    @ResponseWrapper(localName = "addShedResponse", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.AddShedResponse")
    @Action(input = "http://soap.sheds.APP2.introsde/ShedWebService/addShedRequest", output = "http://soap.sheds.APP2.introsde/ShedWebService/addShedResponse")
    public Shed addShed(
        @WebParam(name = "arg0", targetNamespace = "")
        Shed arg0);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.APP4.orchestrator.wsdl.app2shed.Shed>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShedList", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.GetShedList")
    @ResponseWrapper(localName = "getShedListResponse", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.GetShedListResponse")
    @Action(input = "http://soap.sheds.APP2.introsde/ShedWebService/getShedListRequest", output = "http://soap.sheds.APP2.introsde/ShedWebService/getShedListResponse")
    public List<Shed> getShedList();

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.APP4.orchestrator.wsdl.app2shed.Shed
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateShed", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.UpdateShed")
    @ResponseWrapper(localName = "updateShedResponse", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.UpdateShedResponse")
    @Action(input = "http://soap.sheds.APP2.introsde/ShedWebService/updateShedRequest", output = "http://soap.sheds.APP2.introsde/ShedWebService/updateShedResponse")
    public Shed updateShed(
        @WebParam(name = "arg0", targetNamespace = "")
        Shed arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.APP4.orchestrator.wsdl.app2shed.Shed
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShedById", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.GetShedById")
    @ResponseWrapper(localName = "getShedByIdResponse", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.GetShedByIdResponse")
    @Action(input = "http://soap.sheds.APP2.introsde/ShedWebService/getShedByIdRequest", output = "http://soap.sheds.APP2.introsde/ShedWebService/getShedByIdResponse")
    public Shed getShedById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<introsde.APP4.orchestrator.wsdl.app2shed.Shed>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShedByName", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.GetShedByName")
    @ResponseWrapper(localName = "getShedByNameResponse", targetNamespace = "http://soap.sheds.APP2.introsde/", className = "introsde.APP4.orchestrator.wsdl.app2shed.GetShedByNameResponse")
    @Action(input = "http://soap.sheds.APP2.introsde/ShedWebService/getShedByNameRequest", output = "http://soap.sheds.APP2.introsde/ShedWebService/getShedByNameResponse")
    public List<Shed> getShedByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
