
package introsde.APP4.orchestrator.wsdl.app1parks;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ParkImplService", targetNamespace = "http://soap.parks.APP1.introsde/", wsdlLocation = "http://localhost:6900/app1/park?wsdl")
public class ParkImplService
    extends Service
{

    private final static URL PARKIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARKIMPLSERVICE_EXCEPTION;
    private final static QName PARKIMPLSERVICE_QNAME = new QName("http://soap.parks.APP1.introsde/", "ParkImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6900/app1/park?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARKIMPLSERVICE_WSDL_LOCATION = url;
        PARKIMPLSERVICE_EXCEPTION = e;
    }

    public ParkImplService() {
        super(__getWsdlLocation(), PARKIMPLSERVICE_QNAME);
    }

    public ParkImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARKIMPLSERVICE_QNAME, features);
    }

    public ParkImplService(URL wsdlLocation) {
        super(wsdlLocation, PARKIMPLSERVICE_QNAME);
    }

    public ParkImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARKIMPLSERVICE_QNAME, features);
    }

    public ParkImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParkImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ParkWebService
     */
    @WebEndpoint(name = "ParkImplPort")
    public ParkWebService getParkImplPort() {
        return super.getPort(new QName("http://soap.parks.APP1.introsde/", "ParkImplPort"), ParkWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ParkWebService
     */
    @WebEndpoint(name = "ParkImplPort")
    public ParkWebService getParkImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.parks.APP1.introsde/", "ParkImplPort"), ParkWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARKIMPLSERVICE_EXCEPTION!= null) {
            throw PARKIMPLSERVICE_EXCEPTION;
        }
        return PARKIMPLSERVICE_WSDL_LOCATION;
    }

}
