
package introsde.APP4.orchestrator.wsdl.app1parks;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ParkWebService", targetNamespace = "http://soap.parks.APP1.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ParkWebService {


    /**
     * 
     * @return
     *     returns java.util.List<introsde.APP4.orchestrator.wsdl.app1parks.Park>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getParkList", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.GetParkList")
    @ResponseWrapper(localName = "getParkListResponse", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.GetParkListResponse")
    @Action(input = "http://soap.parks.APP1.introsde/ParkWebService/getParkListRequest", output = "http://soap.parks.APP1.introsde/ParkWebService/getParkListResponse")
    public List<Park> getParkList();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorldAsString", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.GetHelloWorldAsString")
    @ResponseWrapper(localName = "getHelloWorldAsStringResponse", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.GetHelloWorldAsStringResponse")
    @Action(input = "http://soap.parks.APP1.introsde/ParkWebService/getHelloWorldAsStringRequest", output = "http://soap.parks.APP1.introsde/ParkWebService/getHelloWorldAsStringResponse")
    public String getHelloWorldAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.APP4.orchestrator.wsdl.app1parks.Park
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPark", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.AddPark")
    @ResponseWrapper(localName = "addParkResponse", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.AddParkResponse")
    @Action(input = "http://soap.parks.APP1.introsde/ParkWebService/addParkRequest", output = "http://soap.parks.APP1.introsde/ParkWebService/addParkResponse")
    public Park addPark(
        @WebParam(name = "arg0", targetNamespace = "")
        Park arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.APP4.orchestrator.wsdl.app1parks.Park
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePark", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.UpdatePark")
    @ResponseWrapper(localName = "updateParkResponse", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.UpdateParkResponse")
    @Action(input = "http://soap.parks.APP1.introsde/ParkWebService/updateParkRequest", output = "http://soap.parks.APP1.introsde/ParkWebService/updateParkResponse")
    public Park updatePark(
        @WebParam(name = "arg0", targetNamespace = "")
        Park arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns introsde.APP4.orchestrator.wsdl.app1parks.Park
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getParkById", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.GetParkById")
    @ResponseWrapper(localName = "getParkByIdResponse", targetNamespace = "http://soap.parks.APP1.introsde/", className = "introsde.APP4.orchestrator.wsdl.app1parks.GetParkByIdResponse")
    @Action(input = "http://soap.parks.APP1.introsde/ParkWebService/getParkByIdRequest", output = "http://soap.parks.APP1.introsde/ParkWebService/getParkByIdResponse")
    public Park getParkById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
